#!/bin/bash

usage() {
    echo 'USAGE'
    echo '    topdf [OPTIONS] INPUT_FILE -- [PANDOC_OPTIONS...]'
    echo
    echo 'OPTIONS'
    echo '    --wkhtml  Use wkhtmltopdf as the PDF engine'
    echo '    --weasy   Use weasyprint as the PDF engine'
    echo '    --latex   Use pdflatex as the PDF engine'
}

if ! command -v pandoc &> /dev/null; then
    echo "Please install pandoc in order to convert to PDF."
    exit 1
fi

in_file=
pdf_engine=wkhtmltopdf
pandoc_options=

while [ -n "$1" ]; do
    case "$1" in
        --wkhtml )
            pdf_engine='wkhtmltopdf'
            ;;
        --weasy )
            pdf_engine='weasyprint'
            ;;
        --latex )
            pdf_engine='pdflatex'
            ;;
        -- )
            shift
            pandoc_options="$@"
            break
            ;;
        * )
            if [ -n "$in_file" ]; then
                usage
                exit 1
            else
                in_file="$1"
            fi
            ;;
    esac

    shift
done

if [ -z "$in_file" ]; then
    usage
    exit 1
fi

# determine output filename from input file
filename=$(basename -- "$in_file")
out_file="${filename%.*}".pdf

# use style.css if present
if [ -f "style.css" ]; then
    pandoc_options="--css=style.css $pandoc_options"
fi

# use specified PDF engine
if [ -n "$pdf_engine" ]; then
    if [ "$pdf_engine" = wkhtmltopdf ]; then
        pandoc_options="--pdf-engine-opt=--enable-local-file-access $pandoc_options"
    fi

    pandoc_options="--pdf-engine=$pdf_engine $pandoc_options"
fi

base_css="$(dirname $(realpath "$0"))/styles/base.css"

echo Converting "$in_file" to "$out_file"...

pandoc \
    --standalone \
    --variable=margin-left:1in \
    --variable=margin-right:1in \
    --variable=margin-top:1in \
    --variable=margin-bottom:1in \
    --variable=papersize:letter \
    --output="$out_file" \
    $pandoc_options \
    "$in_file" \
    <(echo "<style>" && cat "$base_css" && echo "</style>")

